classDiagram
    namespace UI {
        class ConsoleRenderer {
            -Board _board
            -string _eventMessage
            -GameController _gameController
            +ConsoleRenderer(GameController gameController) void
            +Render() void
            +MoveEvent(object? o, MoveEventArgs e) void
        }
    }

    namespace DTOs {
        class GameResponseDto {
            +bool Success
            +Player CurrentPlayer
            +Player? Winner
            +Board Board 
        }

        class CreateGameDto {
            +string PlayerOneName
            +string PlayerTwoName
            +ConsoleColor PlayerOnePreferenceColor
            +ConsoleColor PlayerTwoPreferenceColor
            +BoardSize Size
        }

        class UpdatePiecePositionDto {
            +Position FromPosition
            +Position ToPosition
        }
    }

    namespace Controllers {
        class GameController {
            -bool _crowned,
            -bool _captured,
            -bool _hasMoreCaptured
            -IGameService _gameService            
            +event EventHandler~MoveEventArgs~? MoveMade
            +event EventHandler~GameEndedEventArgs~? GameEnded
            +GameController(GameService gameService) void
            +Start(CreateGameDto dto) GameResponseDto
            +Move(UpdatePositionDto dto, _crowned, _captured, _hasMoreCaptured) GameResponseDto
            -EndGame(Player winner, string reason) void
        }
    }
    
    namespace Services {
        class IGameService {
            <<interface>>
            +GetPieceAt(Position position) Piece?
            +TryMove(UpdatePiecePositionDto dto, out bool crowned, out bool captured, out bool hasMoreCapture) bool
            +AllPieces() IEnumerable~Piece~
            +GetLegalMoves(Player player) IEnumerable~LegalMove~
            +GetLegalMoves(Piece piece) IEnumerable~LegalMove~
            +HasCaptureMoves(Player player) bool
            +HasAnyMoves(Player player) bool
        }
        
        class GameService {
            -Board _board
            +List~Player~ Player
            +Player CurrentPlayer
            +GameService(CreateGameDto dto)
            -PerformMove(Piece piece, int toX, int toY, out bool crowned, out bool capture, out bool hasMoreCapture) void
            -IsInside(int x, int y) bool
        }
    }
    
    namespace Models {
        class Board {
            +Cell[,] Cell 
            +BoardSize Size
            
            +Board(BoardSize Size)
        }

        class Cell {
            +Position Position
            +Piece? Piece
        }

        class Piece {
            +PieceType PieceType
            +ConsoleColor Color 
            +Player Player
        }

        class Player {
            +string Name
            +bool IsPlayerOne    
        }
    }

    namespace Structs {
        class Position{
            + int X
            + int Y
        }
    }

    namespace Events {
        class MoveEventArgs {
            +Player Player
            +Position FromPosition
            +Position ToPosition
            +Piece Piece
            +bool Crowned
        }

        class GameEndedEventArgs {
            +Player Winner
            +string Reason
        }
    }

    namespace Enums {
        class ConsoleColor {
            <<enumeration>>
        }

        class BoardSize {
            <<enumeration>>
            Small
            Standard
            Large
            VeryLarge
        }

        class PieceType {
            <<enumeration>>
            Man
            King
        }
    }

    ConsoleRenderer --> GameController : calls 
    GameController --> IGameService : uses
    GameController --> MoveEventArgs : uses
    GameController --> GameEndedEventArgs : uses
    GameController ..> GameResponseDto: depends on
    GameController ..> CreateGameDto: depends on
    GameController ..> UpdatePiecePositionDto: depends on
    GameService ..|> IGameService: implements
    GameService ..> CreateGameDto: depends on
    GameService --> Board : uses
    Board *-- "0..*" Cell: has
    Cell *-- "0..1" Piece: has
    Piece --> "1"  Player: belongs to